### ISSUE TITLE
dcast() error: Aggregate function missing, defaulting to 'length'

### ISSUE THREAD

**Issue by MattheneusHTA** [InnovationValueInitiative/hesim#5] opened 2019-02-03 17:36 UTC
I get the above error when trying to execute this:
nmb_dt <- dcast(ce[sample %in% random_rows & grp == "group 1"], 
                sample ~ strategy_id, value.var = "nmb")

Could you please assist?
Kind regards
Paul

**Comment by dincerti** [comment] 2019-02-03 18:06
Hi Paul, please provide the minimum necessary reproducible code that documents the error/warning, otherwise it is nearly impossible to diagnose.

**Comment by MattheneusHTA** [comment] 2019-02-03 19:52
Sorry for that, I tried to send the dataset but could not attach it. Here is the code:

random_rows <- sample(1:n_samples, 10)
nmb_dt <- dcast(ce_apa[sample %in% random_rows & patient_id == "PSADT≤6"], 
                sample ~ strategy_id, value.var = "nmb")
setnames(nmb_dt, colnames(nmb_dt), c("sample", "nmb1", "nmb2", "nmb3"))
nmb_dt <- nmb_dt[, maxj := apply(nmb_dt[, .(nmb1, nmb2, nmb3)], 1, which.max)]
nmb_dt <- nmb_dt[, maxj := factor(maxj, levels = c(1, 2, 3))]

And here is the structure of the dataset:
Classes ‘data.table’ and 'data.frame':	1200 obs. of  9 variables:
 $ sample     : num  1 1 1 1 1 1 1 1 1 1 ...
 $ strategy_id: chr  "Apa" "Apa" "Apa" "Apa" ...
 $ patient_id : chr  "PSADT≤6" "PSADT≤6" "PSADT≥6" "PSADT≥6" ...
 $ state_id   : int  1 2 1 2 1 2 1 2 1 2 ...
 $ dr         : num  0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 0.03 ...
 $ qalys      : num  0.457 0.476 0.506 0.395 0.496 ...
 $ category   : chr  "drug" "drug" "drug" "drug" ...
 $ total_costs: num  78287 94691 88154 79775 90815 ...
 $ nmb        : num  333223 334073 367339 275444 355917 ...
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, "sorted")= chr "sample"
 - attr(*, "index")= atomic  
  ..- attr(*, "__patient_id__sample")= int  1 2 5 6 9 10 13 14 17 18 ...

I can send the dataset itself as well.. please advise

**Comment by dincerti** [comment] 2019-03-23 16:33
Hi Paul, since this is a question about using dcast rather than a hesim issue, I'm going to close this. That said, I suspect the issue is that the ce_apa dataset is not aggregated across state_id.

**Closed by dincerti** 2019-03-23 16:33 UTC
